const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),querystring=require('querystring');
const {port,sessionSecret,defaultPassword,dataDir}=require('./config'); const store=require('./store'); const {hashPassword,verifyPassword,sign,verify,cookieSerialize}=require('./auth'); store.init();
const root=path.join(__dirname,'..','public');
function readBody(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>12*1024*1024)req.destroy()});req.on('end',()=>resolve(b));req.on('error',reject)})}
function json(res,obj,status=200){const b=JSON.stringify(obj);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(b)}
function getUser(req){const c=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('medsim_session='));const p=c&&verify(c.slice('medsim_session='.length),sessionSecret);return p&&store.users().find(u=>u.id===p.id&&u.active)}
function auth(req,res){const u=getUser(req);if(!u){json(res,{error:'Authentication required'},401);return null}return u}
function clean(s){const y={...s};delete y.email;delete y.user_id;return y}
function csvParse(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i],n=text[i+1];if(q){if(ch==='"'&&n==='"'){cell+='"';i++}else if(ch==='"')q=false;else cell+=ch}else{if(ch==='"')q=true;else if(ch===','){row.push(cell);cell=''}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=ch}}if(cell.length||row.length){row.push(cell.replace(/\r$/,''));rows.push(row)}if(!rows.length)return[];const headers=rows.shift().map(x=>x.trim());return rows.filter(r=>r.some(x=>x!=='')).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])))}
function normalize(rows){return rows.map(x=>{const y={...x};for(const k of ['messages','review'])if(typeof y[k]==='string'){try{y[k]=JSON.parse(y[k])}catch{y[k]=null}}delete y.email;return y})}
function route(req,res){const u=new URL(req.url,'http://localhost');const p=u.pathname,method=req.method;
if(method==='POST'&&p==='/api/login')return readBody(req).then(b=>{const x=JSON.parse(b||'{}'),user=store.users().find(v=>v.username===x.username&&v.active);if(!user||!verifyPassword(x.password||'',user.password))return json(res,{error:'Invalid username or password'},401);const t=sign({id:user.id,exp:Date.now()+8*60*60*1000},sessionSecret);res.writeHead(200,{'Content-Type':'application/json','Set-Cookie':cookieSerialize('medsim_session',t,8*60*60)});res.end(JSON.stringify({user:safeUser(user)}))});
if(method==='POST'&&p==='/api/logout'){res.writeHead(200,{'Content-Type':'application/json','Set-Cookie':cookieSerialize('medsim_session','',0)});return res.end('{"ok":true}')}
const user=auth(req,res);if(!user)return;
if(method==='GET'&&p==='/api/me')return json(res,{user:safeUser(user)});
if(method==='GET'&&p==='/api/cases'){const ss=store.sessions(),rv=store.read('reviews.json',{}),st=store.read('session-status.json',{});return json(res,store.cases().map(c=>{const a=ss.filter(s=>s.case_uuid===c.id),counts={completed:0,inReview:0,notReviewed:0};for(const s of a){const z=st[s.id]?.[user.id]||'notReviewed';counts[z==='completed'?'completed':z==='inReview'?'inReview':'notReviewed']++}return {...c,counts}}))}
let m=p.match(/^\/api\/cases\/([^/]+)\/sessions$/);if(method==='GET'&&m){const id=decodeURIComponent(m[1]),rv=store.read('reviews.json',{}),st=store.read('session-status.json',{});return json(res,store.sessions().filter(s=>s.case_uuid===id).map(s=>({id:s.id,title:s.title,timestamp:s.timestamp,score:s.score,chat_duration:s.chat_duration,hints_used:s.hints_used,diagnosis:s.diagnosis,status:st[s.id]?.[user.id]||'notReviewed',reviewed:!!rv[s.id]?.[user.id]})))}
m=p.match(/^\/api\/sessions\/([^/]+)$/);if(method==='GET'&&m){const s=store.sessions().find(x=>x.id===decodeURIComponent(m[1]));if(!s)return json(res,{error:'Session not found'},404);const rv=store.read('reviews.json',{}),st=store.read('session-status.json',{});return json(res,{...clean(s),doctorReview:rv[s.id]?.[user.id]||null,status:st[s.id]?.[user.id]||'notReviewed'})}
m=p.match(/^\/api\/sessions\/([^/]+)\/(autosave|review)$/);if(method==='PUT'&&m){const s=store.sessions().find(x=>x.id===decodeURIComponent(m[1]));if(!s)return json(res,{error:'Session not found'},404);return readBody(req).then(b=>{const body=JSON.parse(b||'{}'),rv=store.read('reviews.json',{});rv[s.id] ||= {};rv[s.id][user.id]={...(rv[s.id][user.id]||{}),...body,savedAt:new Date().toISOString()};store.write('reviews.json',rv);const st=store.read('session-status.json',{});st[s.id] ||= {};st[s.id][user.id]=m[2]==='review'?'completed':'inReview';store.write('session-status.json',st);json(res,{ok:true,status:st[s.id][user.id],review:rv[s.id][user.id]})})}
if(user.role==='admin'&&method==='GET'&&p==='/api/admin/stats'){const ss=store.sessions(),us=store.users().filter(x=>x.role==='doctor'),rv=store.read('reviews.json',{});let n=0;for(const s of ss)for(const id of Object.keys(rv[s.id]||{}))if(us.some(x=>x.id===id))n++;return json(res,{sessions:ss.length,cases:store.cases().length,doctors:us.length,reviews:n,meanScore:ss.length?+(ss.reduce((a,s)=>a+(Number(s.score)||0),0)/ss.length).toFixed(2):0,meanDuration:ss.length?+(ss.reduce((a,s)=>a+(Number(s.chat_duration)||0),0)/ss.length).toFixed(1):0})}
if(user.role==='admin'&&method==='GET'&&p==='/api/admin/doctors')return json(res,store.users().filter(x=>x.role==='doctor').map(safeUser));
if(user.role==='admin'&&method==='POST'&&p==='/api/admin/doctors')return readBody(req).then(b=>{const x=JSON.parse(b||'{}'),us=store.users();if(!x.name||!x.username)return json(res,{error:'Name and username are required'},400);if(us.some(v=>v.username.toLowerCase()===x.username.toLowerCase()))return json(res,{error:'Username already exists'},409);const u={id:crypto.randomUUID(),username:x.username,name:x.name,role:'doctor',password:hashPassword(defaultPassword),active:true,createdAt:new Date().toISOString()};us.push(u);store.write('users.json',us);json(res,safeUser(u))});
m=p.match(/^\/api\/admin\/doctors\/([^/]+)$/);if(user.role==='admin'&&m&&(method==='PUT'||method==='DELETE')){const us=store.users(),d=us.find(x=>x.id===m[1]&&x.role==='doctor');if(!d)return json(res,{error:'Doctor not found'},404);if(method==='DELETE')d.active=false;else return readBody(req).then(b=>{const x=JSON.parse(b||'{}');if(x.name)d.name=x.name;if(x.username)d.username=x.username;if(x.active!==undefined)d.active=!!x.active;store.write('users.json',us);json(res,safeUser(d))});store.write('users.json',us);return json(res,{ok:true})}
if(user.role==='admin'&&method==='POST'&&p==='/api/admin/import-csv')return readBody(req).then(b=>{try{const x=JSON.parse(b||'{}'),rows=csvParse(x.csv||'');if(!rows.length||!('id' in rows[0]))throw Error('CSV must contain an id column');const data=normalize(rows);store.write('imported-sessions.json',data);const map=new Map();for(const s of data){const id=s.case_uuid||s.title||s.id;let c=map.get(id);if(!c){c={id,title:s.title||'Untitled Case',sessionCount:0,diagnoses:[]};map.set(id,c)}c.sessionCount++;if(s.diagnosis&&!c.diagnoses.includes(s.diagnosis))c.diagnoses.push(s.diagnosis)}store.write('cases.json',[...map.values()]);json(res,{ok:true,sessions:data.length,cases:map.size})}catch(e){json(res,{error:e.message},400)}});
if(user.role==='admin'&&method==='GET'&&p==='/api/admin/export'){const ss=store.sessions(),rv=store.read('reviews.json',{}),us=store.users().filter(x=>x.role==='doctor'),out=[];for(const s of ss)for(const d of us){const r=rv[s.id]?.[d.id];if(r)out.push({session_id:s.id,case_uuid:s.case_uuid,case_title:s.title,session_timestamp:s.timestamp,doctor_username:d.username,doctor_name:d.name,questionnaire_1:JSON.stringify(r.q1||{}),questionnaire_2:JSON.stringify(r.q2||{}),questionnaire_3:JSON.stringify(r.q3||{}),saved_at:r.savedAt||''})}const h=['session_id','case_uuid','case_title','session_timestamp','doctor_username','doctor_name','questionnaire_1','questionnaire_2','questionnaire_3','saved_at'],e=v=>'"'+String(v??'').replace(/"/g,'""')+'"',csv=h.join(',')+'\n'+out.map(r=>h.map(k=>e(r[k])).join(',')).join('\n');res.writeHead(200,{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="medsim-research-export.csv"'});return res.end(csv)}
return staticFile(p,res)}
function safeUser(u){return{id:u.id,username:u.username,name:u.name,role:u.role,active:u.active,createdAt:u.createdAt}}
function staticFile(p,res){let f=p==='/'?'/index.html':p;if(f.includes('..'))return json(res,{error:'Not found'},404);const fp=path.join(root,f);fs.readFile(fp,(e,b)=>{if(e)return json(res,{error:'Not found'},404);const ext=path.extname(fp),ct={'.html':'text/html','.js':'text/javascript','.css':'text/css'}[ext]||'text/plain';res.writeHead(200,{'Content-Type':ct+'; charset=utf-8'});res.end(b)})}
http.createServer((req,res)=>{route(req,res).catch(e=>json(res,{error:e.message},500))}).listen(port,()=>console.log(`MedSim running at http://localhost:${port}`));
